/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BethakRouteImport } from './routes/bethak'
import { Route as PanLabRouteImport } from './routes/pan-lab'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BethakRoute = BethakRouteImport.update({
  id: '/bethak',
  path: '/bethak',
  getParentRoute: () => rootRouteImport,
} as any)
const PanLabRoute = PanLabRouteImport.update({
  id: '/pan-lab',
  path: '/pan-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bethak': typeof BethakRoute
  '/pan-lab': typeof PanLabRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bethak': typeof BethakRoute
  '/pan-lab': typeof PanLabRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bethak': typeof BethakRoute
  '/pan-lab': typeof PanLabRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bethak' | '/pan-lab' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bethak' | '/pan-lab' | '/sitemap.xml'
  id: '__root__' | '/' | '/bethak' | '/pan-lab' | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BethakRoute: typeof BethakRoute
  PanLabRoute: typeof PanLabRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bethak': {
      id: '/bethak'
      path: '/bethak'
      fullPath: '/bethak'
      preLoaderRoute: typeof BethakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pan-lab': {
      id: '/pan-lab'
      path: '/pan-lab'
      fullPath: '/pan-lab'
      preLoaderRoute: typeof PanLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BethakRoute: BethakRoute,
  PanLabRoute: PanLabRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
